### ISSUE TITLE
Ability to use custom output directory/filename prefix in simple mode

### ISSUE THREAD

**Issue by culinko** [andburn/hdt-plugin-endgame#2]
Hello again, I would like to request the ability to set custom output directory and custom filename prefix in simple mode as well. I would like to save only one screenshot and without any note popups. Thanks!

**Comment by andburn** [comment]
Simple mode doesn't work very well, so I'll probably leave it as it is. I could change how the Advanced mode works, so that if *Image Number* is set to 1 then it doesn't show the dialog and just saves the image according to other advanced settings.

**Comment by culinko** [comment]
This would be awesome. I tried the advanced mode with only 1 image and after I confirmed the dialog, the screenshot didn't save. So that's why I resorted to using simple mode and I have to manually rename the sceens and move them to my desired location.

**Comment by andburn** [comment]
This should work now. I eventually updated the plugin :smile:, there should be a notification when you open the tracker when the plugin is enabled. The naming pattern/prefix is optional, its there in case people might want to add something like "*fireside-august_*" to the start of your screenshots.

**Comment by culinko** [comment]
Alright, gave the new version a shot. There are a couple of issues I've found. I will list them here. I can make separate tickets for them if needed.

- I still get the update prompt even though I'm already using the newest version
- If you have Advanced mode unchecked and restart the tracker, you can change settings in "Game Modes" section, even though it should be possible only with Advanced mode enabled
- I still can't get Advanced mode to work. However, this seems to be related to the config file. It seems that the values in HDT.Plugins.EndGame.Properties.Settings (OutputDir, FilePrefix, UseAdvancedShot, NumberOfImages and all the game mode settings) are still the default ones.

Let me know if there is something more I could do to help.

**Comment by andburn** [comment]
Ok, thanks for testing it out. I'll have a look at it now.

**Comment by andburn** [comment]
I've updated it again, with corrections for the first two points.

To try and get it working, this time delete the existing *EndGame* folder and all its contents, from the HDT plugins folder. 
Also, delete the user settings, which are stored in `C:\Users\<username>\AppData\Local\Epix` in that folder there should be a number of folders starting with *Hearthstone_Deck_Tracker...*, if there is only one such folder delete it and all its contents. If there is more than one, you'll have to go into each of them and open the `0.1.0.0\app.config` file and check if it has `HDT.Plugins.EndGame.Properties.Settings` in it, then delete all such folders and their contents.
Then start up as normal.

Let me know how it goes.

**Comment by culinko** [comment]
Thanks a lot for the quick fixes! Downloaded 0.2.2 and I can confirm all 3 issues I listed being fixed. Advanced mode not saving screenshots was my fault, I was using some dumb prefix, sorry. (Also I didn't realize the user setting file is in Appdata and not in plugin directory).

I have a last request, though. Would it be possible to let user specify the naming pattern instead of just a custom prefix? I'm thinking about "PlayerName (class) vs OppName (class) {Date dd.MM.yyyy HH:mm}" or something like that. This would be the last thing I'd want from you :)

**Comment by andburn** [comment]
Added a naming pattern option, check it out.

**Comment by culinko** [comment]
The addition is awesome!

Howeve, I tested my pattern "{PlayerName} ({PlayerClass}) vs {OpponentName} ({OpponentClass}) {Date:MM-dd-yy HH.mm.ss}" by conceding in Practice mode, but it didn't save the screenshot. This line appears in the HDT log though: "[18:41:56] EndGame: Capture (Advanced) @ 500000/500". I will try to test it in ranked later.

**Comment by andburn** [comment]
The log line is just for info, it just shows what the current *Dealy/Spacing* values are. You have the  *Delay* set to 500 seconds, so something probably timeout before the file was saved. The *Delay* value is in seconds (default 6), and the *Spacing* is in milliseconds (default 500). If you are only capturing the one image, you'll only need to tweak the *Delay* value.
